program_options:
  automount: true        # wichtig: automatisch einh√§ngen
  notify: true
  tray: auto             # oder "smart-tray"
notifications:
  device_added: false    # reduzierte Popups
  device_removed: true
  device_mounted: true
  device_unmounted: true
  job_failed: true
